from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any


@dataclass(frozen=True, slots=True)
class ParamSpec:
    key: str
    label: str
    default: float
    minimum: float
    maximum: float
    recommended_min: float
    recommended_max: float
    step: float
    unit: str
    description: str

    def to_schema(self) -> dict[str, Any]:
        return asdict(self)


CONTROL_PARAM_SPECS: dict[str, ParamSpec] = {
    "control.experimental_angle_kp_x": ParamSpec(
        key="control.experimental_angle_kp_x",
        label="Kp X",
        default=0.35,
        minimum=0.0,
        maximum=2.0,
        recommended_min=0.20,
        recommended_max=0.60,
        step=0.01,
        unit="",
        description="角度域 X 轴比例增益，越大横向响应越快，但更容易过冲。",
    ),
    "control.experimental_angle_kp_y": ParamSpec(
        key="control.experimental_angle_kp_y",
        label="Kp Y",
        default=0.24,
        minimum=0.0,
        maximum=2.0,
        recommended_min=0.15,
        recommended_max=0.45,
        step=0.01,
        unit="",
        description="角度域 Y 轴比例增益，通常应低于 X 轴，避免垂直方向抖动。",
    ),
    "control.experimental_angle_kd": ParamSpec(
        key="control.experimental_angle_kd",
        label="Kd",
        default=0.0,
        minimum=-1.0,
        maximum=1.0,
        recommended_min=0.0,
        recommended_max=0.25,
        step=0.01,
        unit="",
        description="角度域阻尼系数，先从 0 开始；绝对值过大会放大检测抖动。",
    ),
    "control.experimental_angle_deadzone_px": ParamSpec(
        key="control.experimental_angle_deadzone_px",
        label="Dead Zone",
        default=0.0,
        minimum=0.0,
        maximum=100.0,
        recommended_min=0.0,
        recommended_max=8.0,
        step=1.0,
        unit="px",
        description="控制坐标系像素死区，误差进入该范围后停止输出。",
    ),
    "control.experimental_angle_max_step_counts": ParamSpec(
        key="control.experimental_angle_max_step_counts",
        label="Max Step",
        default=80.0,
        minimum=1.0,
        maximum=500.0,
        recommended_min=30.0,
        recommended_max=120.0,
        step=1.0,
        unit="count",
        description="角度控制结果换算为 kmNet counts 后的单次向量限幅。",
    ),
    "control.experimental_angle_max_control_angle_deg": ParamSpec(
        key="control.experimental_angle_max_control_angle_deg",
        label="Max Angle",
        default=3.0,
        minimum=0.001,
        maximum=15.0,
        recommended_min=1.0,
        recommended_max=5.0,
        step=0.1,
        unit="deg",
        description="Angular PD 输出在映射 counts 前的角度向量限幅，防止远距离误差单帧输出过大。",
    ),
    "control.experimental_angle_max_counts_delta_x": ParamSpec(
        key="control.experimental_angle_max_counts_delta_x",
        label="Slew X",
        default=35.0,
        minimum=1.0,
        maximum=300.0,
        recommended_min=15.0,
        recommended_max=80.0,
        step=1.0,
        unit="count",
        description="相邻控制命令 X 轴 counts 变化上限，用于抑制突然跳变。",
    ),
    "control.experimental_angle_max_counts_delta_y": ParamSpec(
        key="control.experimental_angle_max_counts_delta_y",
        label="Slew Y",
        default=35.0,
        minimum=1.0,
        maximum=300.0,
        recommended_min=10.0,
        recommended_max=60.0,
        step=1.0,
        unit="count",
        description="相邻控制命令 Y 轴 counts 变化上限，用于抑制突然跳变。",
    ),
    "control.experimental_angle_near_error_deg": ParamSpec(
        key="control.experimental_angle_near_error_deg",
        label="Near Zone",
        default=0.35,
        minimum=0.0,
        maximum=10.0,
        recommended_min=0.15,
        recommended_max=0.80,
        step=0.05,
        unit="deg",
        description="进入近区的角误差半径，近区通常降低 P 并保留更多阻尼。",
    ),
    "control.experimental_angle_far_error_deg": ParamSpec(
        key="control.experimental_angle_far_error_deg",
        label="Far Zone",
        default=2.50,
        minimum=0.0,
        maximum=30.0,
        recommended_min=1.5,
        recommended_max=5.0,
        step=0.1,
        unit="deg",
        description="进入远区的角误差半径，远区通常保持更高 P 响应。",
    ),
    "control.experimental_angle_near_kp_scale": ParamSpec(
        key="control.experimental_angle_near_kp_scale",
        label="Near Kp",
        default=0.35,
        minimum=0.0,
        maximum=3.0,
        recommended_min=0.20,
        recommended_max=0.70,
        step=0.01,
        unit="x",
        description="近区 P 增益倍率，降低接近目标时的过冲。",
    ),
    "control.experimental_angle_middle_kp_scale": ParamSpec(
        key="control.experimental_angle_middle_kp_scale",
        label="Mid Kp",
        default=0.70,
        minimum=0.0,
        maximum=3.0,
        recommended_min=0.45,
        recommended_max=1.0,
        step=0.01,
        unit="x",
        description="中区 P 增益倍率，控制追踪过渡区响应。",
    ),
    "control.experimental_angle_far_kp_scale": ParamSpec(
        key="control.experimental_angle_far_kp_scale",
        label="Far Kp",
        default=1.00,
        minimum=0.0,
        maximum=3.0,
        recommended_min=0.80,
        recommended_max=1.50,
        step=0.01,
        unit="x",
        description="远区 P 增益倍率，决定大误差时的追赶力度。",
    ),
    "control.experimental_angle_near_kd_scale": ParamSpec(
        key="control.experimental_angle_near_kd_scale",
        label="Near Kd",
        default=1.00,
        minimum=0.0,
        maximum=3.0,
        recommended_min=0.70,
        recommended_max=1.50,
        step=0.01,
        unit="x",
        description="近区 D 增益倍率，接近目标时用于抑制抖动和过冲。",
    ),
    "control.experimental_angle_middle_kd_scale": ParamSpec(
        key="control.experimental_angle_middle_kd_scale",
        label="Mid Kd",
        default=0.80,
        minimum=0.0,
        maximum=3.0,
        recommended_min=0.40,
        recommended_max=1.20,
        step=0.01,
        unit="x",
        description="中区 D 增益倍率。",
    ),
    "control.experimental_angle_far_kd_scale": ParamSpec(
        key="control.experimental_angle_far_kd_scale",
        label="Far Kd",
        default=0.50,
        minimum=0.0,
        maximum=3.0,
        recommended_min=0.0,
        recommended_max=0.80,
        step=0.01,
        unit="x",
        description="远区 D 增益倍率，大误差时通常降低阻尼以免响应迟滞。",
    ),
    "control.experimental_angle_prediction_gain_min": ParamSpec(
        key="control.experimental_angle_prediction_gain_min",
        label="Pred P Min",
        default=0.35,
        minimum=0.0,
        maximum=1.0,
        recommended_min=0.20,
        recommended_max=0.60,
        step=0.01,
        unit="",
        description="预测帧最低 P 增益比例，预测可信度越低输出越保守。",
    ),
    "control.experimental_angle_prediction_d_gain_min": ParamSpec(
        key="control.experimental_angle_prediction_d_gain_min",
        label="Pred D Min",
        default=0.25,
        minimum=0.0,
        maximum=1.0,
        recommended_min=0.10,
        recommended_max=0.50,
        step=0.01,
        unit="",
        description="预测帧最低 D 增益比例，避免漏检外推时导数项过度放大。",
    ),
    "control.experimental_angle_control_hz": ParamSpec(
        key="control.experimental_angle_control_hz",
        label="Control Hz",
        default=60.0,
        minimum=1.0,
        maximum=240.0,
        recommended_min=60.0,
        recommended_max=144.0,
        step=1.0,
        unit="Hz",
        description="连续控制线程频率；推理低频更新观测，控制线程按该频率预测并小步输出。",
    ),
}


def param_schema_for(path: str) -> dict[str, Any]:
    spec = CONTROL_PARAM_SPECS.get(path)
    return spec.to_schema() if spec is not None else {}
