from __future__ import annotations

import tempfile
from pathlib import Path

from novasight.model_registry.manifest import ModelManifest


def generate_nvinfer_config(
    manifest: ModelManifest,
    *,
    engine_path: Path,
    parser_library_path: Path,
    confidence_threshold: float | None = None,
    nms_threshold: float | None = None,
) -> str:
    _validate_manifest(manifest)
    confidence = (
        float(manifest.postprocess.confidence_threshold)
        if confidence_threshold is None
        else float(confidence_threshold)
    )
    nms = (
        float(manifest.postprocess.nms_iou_threshold)
        if nms_threshold is None
        else float(nms_threshold)
    )
    lines = [
        "# Generated by NovaSight. Do not hand-edit.",
        f"# novasight-model-fingerprint={manifest.model_fingerprint}",
        "[property]",
        "gpu-id=0",
        f"model-engine-file={Path(engine_path).expanduser().resolve(strict=False)}",
        "batch-size=1",
        f"network-mode={_network_mode(manifest.runtime.precision)}",
        "network-type=0",
        "process-mode=1",
        "gie-unique-id=1",
        "interval=0",
        f"num-detected-classes={int(manifest.output.class_count)}",
        f"net-scale-factor={float(manifest.input.scale_factor):.17g}",
        f"model-color-format={_model_color_format(manifest.input.color_format)}",
        f"maintain-aspect-ratio={int(bool(manifest.input.maintain_aspect_ratio))}",
        f"symmetric-padding={int(bool(manifest.input.symmetric_padding))}",
        "output-tensor-meta=1",
        f"output-blob-names={manifest.output.name}",
        f"custom-lib-path={Path(parser_library_path).expanduser().resolve(strict=False)}",
        "parse-bbox-func-name=NvDsInferParseNovaSight",
        "cluster-mode=2",
        "",
        "[class-attrs-all]",
        f"pre-cluster-threshold={confidence:.8g}",
        f"nms-iou-threshold={nms:.8g}",
        f"topk={max(1, int(manifest.postprocess.max_detections))}",
        "",
    ]
    return "\n".join(lines)


def write_nvinfer_config(
    path: Path,
    manifest: ModelManifest,
    *,
    engine_path: Path,
    parser_library_path: Path,
    confidence_threshold: float | None = None,
    nms_threshold: float | None = None,
) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    text = generate_nvinfer_config(
        manifest,
        engine_path=engine_path,
        parser_library_path=parser_library_path,
        confidence_threshold=confidence_threshold,
        nms_threshold=nms_threshold,
    )
    if not target.exists() or target.read_text(encoding="utf-8") != text:
        temporary: Path | None = None
        try:
            with tempfile.NamedTemporaryFile(
                mode="w",
                encoding="utf-8",
                dir=target.parent,
                prefix=f".{target.name}.",
                suffix=".tmp",
                delete=False,
            ) as handle:
                handle.write(text)
                handle.flush()
                temporary = Path(handle.name)
            temporary.replace(target)
        finally:
            if temporary is not None and temporary.exists():
                temporary.unlink()
    return target


def _validate_manifest(manifest: ModelManifest) -> None:
    if int(manifest.runtime.batch_size) != 1:
        raise ValueError("deepstream_nvinfer requires model batch_size=1")
    if str(manifest.input.layout).upper() != "NCHW" or len(manifest.input.shape) != 4:
        raise ValueError("deepstream_nvinfer requires a four-dimensional NCHW input")
    if str(manifest.postprocess.parser).strip().lower() != "yolo":
        raise ValueError(
            "deepstream_nvinfer raw parser only supports postprocess.parser=yolo; "
            "models with built-in Decode/NMS need an explicit no-second-NMS parser contract"
        )
    if str(manifest.output.format).strip().lower() != "yolo_cxcywh_class_scores":
        raise ValueError(
            "deepstream_nvinfer raw parser only supports yolo_cxcywh_class_scores; "
            "refusing to guess an end-to-end NMS output contract"
        )
    if str(manifest.output.coordinate_mode).strip().lower() != "pixel":
        raise ValueError("NvDsInferParseNovaSight currently requires pixel coordinates")
    if len(manifest.output.shape) not in {2, 3}:
        raise ValueError("YOLO output shape must be [C,N], [N,C], or [1,C,N]")
    class_count = int(manifest.output.class_count)
    if class_count <= 0:
        raise ValueError("model output class_count must be positive")
    dims = [int(value) for value in manifest.output.shape]
    dims = dims[1:] if len(dims) == 3 and dims[0] == 1 else dims
    channels = {4 + class_count, 5 + class_count}
    if len(dims) != 2 or not any(value in channels for value in dims):
        raise ValueError(
            "YOLO output must expose 4+classes or 5+classes channels for the native parser"
        )


def _network_mode(value: str) -> int:
    precision = str(value).strip().lower()
    mapping = {"fp32": 0, "int8": 1, "fp16": 2}
    if precision not in mapping:
        raise ValueError(f"unsupported DeepStream precision: {value}")
    return mapping[precision]


def _model_color_format(value: str) -> int:
    color = str(value).strip().upper()
    mapping = {"RGB": 0, "BGR": 1, "GRAY": 2, "GREY": 2}
    if color not in mapping:
        raise ValueError(f"unsupported DeepStream input color format: {value}")
    return mapping[color]


__all__ = ["generate_nvinfer_config", "write_nvinfer_config"]
