[package]
name = "novasightd"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "novasightd"
path = "src/main.rs"

[features]
default = []
deepstream = ["relink-server/deepstream"]
experimental-kmnet-native = ["deepstream", "relink-server/experimental-kmnet-native"]

[dependencies]
relink-server = { path = "../../bins/relink_server" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "sync"] }

[dev-dependencies]
uuid.workspace = true
