[package]
name = "novasight"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "novasight"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
novasight-store = { path = "../../crates/novasight-store" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_yaml.workspace = true
